new: add cart and payment view controller, presenters and services
vovameister/FakeNFT pull request #37
Opened 2024-01-29 22:33 UTC by ulanovakira

2024-01-31 14:10 UTC, ulanovakira commented
Архитектура: MVP
Тип верстки: Код
Ссылка на доску https://github.com/users/vovameister/projects/8/views/1

2024-01-31 18:41 UTC, protos17 requested changes

2024-01-31 18:41 UTC, protos17 commented on FakeNFT/Scenes /Cart/CartTableView.swift
> +        nftsInCart = nfts
Для того, чтобы ячейки в таблице отображались, их необходимо зарегистрировать:

     register(CartTableViewCell.self, forCellReuseIdentifier: CartTableViewCell.reuseId)

2024-01-31 18:41 UTC, protos17 commented on FakeNFT/Scenes /Cart/CartTableViewCell.swift
> +            deleteButton.widthAnchor.constraint(equalToConstant: 40)
Константы для констрейнтов рекомендую выносить в extension класса: 

       extension CartTableViewCell {           
        private enum Constants {          
              static let defaultOffset: CGFloat = 4 0  
                           ...            
                 }       
         }

2024-01-31 18:41 UTC, protos17 commented on FakeNFT/Scenes /Cart/RatingControl.swift
> +class RatingControl: UIStackView {
Рекомендую указать как final

2024-01-31 18:41 UTC, protos17 commented on FakeNFT/Scenes /Payment/PaymentViewController.swift
> +
Рекомендую оставлять не более 1 отступа

2024-01-31 18:41 UTC, protos17 commented on FakeNFT/Scenes /Payment/PaymentViewPresenter.swift
> +        service.loadCurrencies{ result in
Сильная ссылка

2024-02-01 07:57 UTC, protos17 approved these changes

2024-02-01 07:57 UTC, protos17 commented on FakeNFT/Scenes /Payment/PaymentViewCell.swift
> +//        imageView.image = UIImage(named: "Vector")
Лишний закомментированный код рекомендую удалять

2024-02-01 07:57 UTC, protos17 commented on FakeNFT/Scenes /Payment/PaymentViewCell.swift
> +        currencyImageView.kf.setImage(with: URL(string: currency.image), placeholder: UIImage(named: "Vector"))
Необходимо добавить эту картинку "Vector" для заглушки

2024-02-01 07:57 UTC, protos17 commented on FakeNFT/Services/CartService.swift
> +                    self.loadNft(id: $0){ [weak self] result in
Здесь weak self можно убрать, потому что обращения к self нет

2024-02-01 09:14 UTC, merged